package model;
// Generated Oct 28, 2018 7:57:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private int idauthor;
     private String name;
     private String description;
     private Boolean active;
     private Set books = new HashSet(0);

    public Author() {
    }

	
    public Author(int idauthor) {
        this.idauthor = idauthor;
    }
    public Author(int idauthor, String name, String description, Boolean active, Set books) {
       this.idauthor = idauthor;
       this.name = name;
       this.description = description;
       this.active = active;
       this.books = books;
    }
   
    public int getIdauthor() {
        return this.idauthor;
    }
    
    public void setIdauthor(int idauthor) {
        this.idauthor = idauthor;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


